### ISSUE TITLE
Configuration sample

### ISSUE THREAD

**Issue by papakay** [mweibel/facebook.ex#51]
Hello I followed the example in the readme but I got this error.

```
** (ArgumentError) application :facebook is not loaded, or the configuration parameter :appsecret is not set
    (elixir) lib/application.ex:281: Application.fetch_env!/2
    lib/facebook.ex:488: Facebook.add_app_secret/2
    lib/facebook.ex:73: Facebook.me/2
```

Please can you provide a sample mix configuration.

**Comment by papakay** [comment]
I've tried 

```
config :facebook,
   appsecret: "app_secret_token"
```

but i got 

```
** (ArgumentError) application :facebook is not loaded, or the configuration parameter :graph_url is not set
    (elixir) lib/application.ex:281: Application.fetch_env!/2
    lib/facebook/graph.ex:47: Facebook.Graph.get/3
```

Please where do i get that. I think a full configuration will be needed. 

Thanks.

**Comment by papakay** [comment]
Please kindly disregard. I forgot to add faceebook to application start. Please pardon me.
